---
title: "CPR Ocean Plastics Explorer"
resource_files:
- data/data.RDS
- R/setup.R
- R/controls.R
- R/boxplots.R
- R/histogram.R
- R/incid_start.R
- R/incid_end.R
- R/incid_path.R
- R/timeline_start.R
- R/timeline_end.R
- R/timeline_path.R
runtime: shiny
output:
  flexdashboard::flex_dashboard:
    navbar:
    - align: right
      href: mailto:keith.mcnulty@gmail.com
      icon: fa-envelope
      title: Contact App Author
    - href: https://github.com/keithmcnulty/cpr_data
      icon: fa-github
      title: View Code
    orientation: rows
    theme: cerulean
    vertical_layout: scroll
---

```{r setup, include = FALSE, code = readLines('R/setup.R')}

# basic settings and data load

```






Sidebar {.sidebar data-width=300}
===============================================


<br>

<b>Note:</b> When viewing Timelines, ensure to select filters <i>before</i> pressing play.

<br>

``` {r controls, code = readLines('R/controls.R') }

# sidebar UI controls


```



View statistics
===============================================

Row
---------------------------------------

### Incident boxplots

``` {r generate incident boxplots, code = readLines('R/boxplots.R')}

# generate incident boxplots

```


Row
--------------------------------------

### Incident density histogram

``` {r generate incident density histogram, code = readLines('R/histogram.R')}

# generate incident density histogram

```



View Incidents
===============================================


Row {.tabset .tabset-fade data-height=700}
-----------------------------------------------

### Incidents by tow start point

``` {r generate starting point view, code = readLines('R/incid_start.R')}

# generate view by incident start

```

### Incidents by tow end point

``` {r generate end point view, code = readLines('R/incid_end.R')}

# generate view by incident end

```




View Timeline 
===============================================



Row {.tabset .tabset-fade data-height=700}
-----------------------------------------------

### Timeline by tow start point

``` {r generate timeline starting point view, code = readLines('R/timeline_start.R')}

# generate animated timeline by start point

```


### Timeline by tow end point

``` {r generate timeline end point view, code = readLines('R/timeline_end.R')}

# generate animated timeline by end point

```


